/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Ventanas;

import javax.swing.*;
import javax.swing.event.ChangeListener;

/**
 *
 * @author DanKuzo
 */
public class Pedidos extends javax.swing.JFrame {

    int precioReal = 0;
    int PrecioSensilla = 0;
    int PrecioHawaiana = 0;
    int PrecioDoble = 0;
    int PrecioSalsaHab = 0;
    int PrecioDobleHawai = 0;
    int PrecioDobleHab = 0;
    int PrecioEspecial = 0;

    int BrochetaPollo = 0;
    int BrochetaHab = 0;

    int Alitas6 = 0;
    int Alitas12 = 0;
    int Papas = 0;

    /**
     * Creates new form Pedidos
     */
    public Pedidos() {

        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Brochetas = new javax.swing.ButtonGroup();
        Alitas = new javax.swing.ButtonGroup();
        MenuComida = new javax.swing.JTabbedPane();
        HamburguezasMenu = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        HawaianaImg = new javax.swing.JLabel();
        SencillaImg = new javax.swing.JLabel();
        HabaneroImg = new javax.swing.JLabel();
        DobleImg = new javax.swing.JLabel();
        EspecialImg = new javax.swing.JLabel();
        DobleHawaianaImg = new javax.swing.JLabel();
        DobleHabanaeroImg = new javax.swing.JLabel();
        Sencilla = new javax.swing.JCheckBox();
        SencillaCon = new javax.swing.JSpinner();
        HawaianaCon = new javax.swing.JSpinner();
        Hawaiana = new javax.swing.JCheckBox();
        DobleCon = new javax.swing.JSpinner();
        Doble = new javax.swing.JCheckBox();
        HabaneroCon = new javax.swing.JSpinner();
        Habanero = new javax.swing.JCheckBox();
        DobleHawaiana = new javax.swing.JCheckBox();
        DobleHabanero = new javax.swing.JCheckBox();
        jLabel25 = new javax.swing.JLabel();
        Especial = new javax.swing.JCheckBox();
        EspecialCon = new javax.swing.JSpinner();
        DobleHawaianaCon = new javax.swing.JSpinner();
        DobleHabaneroCon = new javax.swing.JSpinner();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        ExtrasMenu = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        BBQ = new javax.swing.JRadioButton();
        MangoHab = new javax.swing.JRadioButton();
        OrdenPapas = new javax.swing.JRadioButton();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        OrdenAlitas12 = new javax.swing.JRadioButton();
        OrdenAlitas6 = new javax.swing.JRadioButton();
        PrecioBrochetas = new javax.swing.JLabel();
        PrecioPapas = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        PrecioAlitas = new javax.swing.JLabel();
        ContenidoPago = new javax.swing.JPanel();
        jLabel33 = new javax.swing.JLabel();
        TotalPagar = new javax.swing.JLabel();
        Pagar = new javax.swing.JButton();
        Regresar = new javax.swing.JButton();
        Agregar = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        MenuComida.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                MenuComidaStateChanged(evt);
            }
        });
        MenuComida.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MenuComidaMouseClicked(evt);
            }
        });
        MenuComida.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                MenuComidaPropertyChange(evt);
            }
        });

        jLabel1.setText("Ranita (Sensilla)");

        jLabel2.setText("Ranita en el estanque");

        jLabel3.setText("(Hawaiana)");

        jLabel4.setText("Ranota (Doble)");

        jLabel5.setText("Ranita en llamas");

        jLabel6.setText("(Con salsa habanaero)");

        jLabel7.setText("Ranita en la Playa");

        jLabel8.setText("(Doble Hawaiana)");

        jLabel9.setText("Ranota Endiablada");

        jLabel10.setText("(Doble Con Salsa Habanaero)");

        jLabel11.setText("Especial Ranota ");

        HawaianaImg.setText("jLabel17");

        SencillaImg.setText("jLabel17");

        HabaneroImg.setText("jLabel17");

        DobleImg.setText("jLabel17");

        EspecialImg.setText("jLabel17");

        DobleHawaianaImg.setText("jLabel17");

        DobleHabanaeroImg.setText("jLabel17");

        Sencilla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SencillaActionPerformed(evt);
            }
        });

        SencillaCon.setEnabled(false);
        SencillaCon.setModel(new javax.swing.SpinnerNumberModel(Integer.valueOf(1), Integer.valueOf(1), null, Integer.valueOf(1)));
        SencillaCon.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                SencillaConStateChanged(evt);
            }
        });

        HawaianaCon.setModel(new javax.swing.SpinnerNumberModel(Integer.valueOf(1), Integer.valueOf(1), null, Integer.valueOf(1)));

        HawaianaCon.setEnabled(false);
        HawaianaCon.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                HawaianaConStateChanged(evt);
            }
        });

        Hawaiana.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HawaianaActionPerformed(evt);
            }
        });

        DobleCon.setModel(new javax.swing.SpinnerNumberModel(Integer.valueOf(1), Integer.valueOf(1), null, Integer.valueOf(1)));

        DobleCon.setEnabled(false);
        DobleCon.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                DobleConStateChanged(evt);
            }
        });

        Doble.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DobleActionPerformed(evt);
            }
        });

        HabaneroCon.setModel(new javax.swing.SpinnerNumberModel(Integer.valueOf(1), Integer.valueOf(1), null, Integer.valueOf(1)));

        HabaneroCon.setEnabled(false);
        HabaneroCon.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                HabaneroConStateChanged(evt);
            }
        });

        Habanero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HabaneroActionPerformed(evt);
            }
        });

        DobleHawaiana.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DobleHawaianaActionPerformed(evt);
            }
        });

        DobleHabanero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DobleHabaneroActionPerformed(evt);
            }
        });

        jLabel25.setText("+ 3 alitas de habanero");

        Especial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EspecialActionPerformed(evt);
            }
        });

        EspecialCon.setModel(new javax.swing.SpinnerNumberModel(Integer.valueOf(1), Integer.valueOf(1), null, Integer.valueOf(1)));

        EspecialCon.setEnabled(false);
        EspecialCon.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                EspecialConStateChanged(evt);
            }
        });

        DobleHawaianaCon.setModel(new javax.swing.SpinnerNumberModel(Integer.valueOf(1), Integer.valueOf(1), null, Integer.valueOf(1)));

        DobleHawaianaCon.setEnabled(false);
        DobleHawaianaCon.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                DobleHawaianaConStateChanged(evt);
            }
        });

        DobleHabaneroCon.setModel(new javax.swing.SpinnerNumberModel(Integer.valueOf(1), Integer.valueOf(1), null, Integer.valueOf(1)));

        DobleHabaneroCon.setEnabled(false);
        DobleHabaneroCon.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                DobleHabaneroConStateChanged(evt);
            }
        });

        jLabel26.setText("Cantidad");

        jLabel27.setText("Cantidad");

        jLabel28.setText("Cantidad");

        jLabel29.setText("Cantidad");

        jLabel30.setText("Cantidad");

        jLabel31.setText("Cantidad");

        jLabel32.setText("Cantidad");

        javax.swing.GroupLayout HamburguezasMenuLayout = new javax.swing.GroupLayout(HamburguezasMenu);
        HamburguezasMenu.setLayout(HamburguezasMenuLayout);
        HamburguezasMenuLayout.setHorizontalGroup(
            HamburguezasMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, HamburguezasMenuLayout.createSequentialGroup()
                .addGroup(HamburguezasMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(HamburguezasMenuLayout.createSequentialGroup()
                        .addGroup(HamburguezasMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(HamburguezasMenuLayout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(Sencilla))
                            .addGroup(HamburguezasMenuLayout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addComponent(SencillaImg, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(SencillaCon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel26)))
                        .addGroup(HamburguezasMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(HamburguezasMenuLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(HamburguezasMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(HamburguezasMenuLayout.createSequentialGroup()
                                        .addGap(29, 29, 29)
                                        .addComponent(jLabel9))
                                    .addComponent(jLabel10))
                                .addGap(6, 6, 6))
                            .addGroup(HamburguezasMenuLayout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(HamburguezasMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, HamburguezasMenuLayout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(Hawaiana)
                                        .addGap(53, 53, 53))
                                    .addGroup(HamburguezasMenuLayout.createSequentialGroup()
                                        .addGroup(HamburguezasMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(HamburguezasMenuLayout.createSequentialGroup()
                                                .addGap(22, 22, 22)
                                                .addComponent(jLabel3)
                                                .addGap(26, 26, 26))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, HamburguezasMenuLayout.createSequentialGroup()
                                                .addComponent(HawaianaImg, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                                        .addComponent(HawaianaCon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabel27)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE))))
                    .addGroup(HamburguezasMenuLayout.createSequentialGroup()
                        .addGroup(HamburguezasMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(HamburguezasMenuLayout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addGroup(HamburguezasMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel8)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, HamburguezasMenuLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(DobleHawaianaImg, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(HamburguezasMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(HamburguezasMenuLayout.createSequentialGroup()
                                .addComponent(DobleHawaiana)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(HamburguezasMenuLayout.createSequentialGroup()
                                .addComponent(DobleHawaianaCon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel30)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(DobleHabanaeroImg, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(35, 35, 35)))))
                .addGroup(HamburguezasMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(HamburguezasMenuLayout.createSequentialGroup()
                        .addGroup(HamburguezasMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(HamburguezasMenuLayout.createSequentialGroup()
                                .addGroup(HamburguezasMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(HamburguezasMenuLayout.createSequentialGroup()
                                        .addComponent(jLabel4)
                                        .addGap(18, 18, 18)
                                        .addComponent(Doble))
                                    .addGroup(HamburguezasMenuLayout.createSequentialGroup()
                                        .addGap(14, 14, 14)
                                        .addComponent(DobleImg, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(DobleCon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(53, 53, 53))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, HamburguezasMenuLayout.createSequentialGroup()
                                .addGap(126, 126, 126)
                                .addComponent(jLabel28)))
                        .addGap(18, 18, 18)
                        .addGroup(HamburguezasMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(HamburguezasMenuLayout.createSequentialGroup()
                                .addGroup(HamburguezasMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6)
                                    .addGroup(HamburguezasMenuLayout.createSequentialGroup()
                                        .addGap(15, 15, 15)
                                        .addComponent(jLabel5)))
                                .addGap(10, 10, 10)
                                .addGroup(HamburguezasMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(HabaneroCon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Habanero)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, HamburguezasMenuLayout.createSequentialGroup()
                                .addGap(37, 37, 37)
                                .addComponent(HabaneroImg, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(42, 42, 42)))
                        .addComponent(jLabel29))
                    .addGroup(HamburguezasMenuLayout.createSequentialGroup()
                        .addGroup(HamburguezasMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(DobleHabanero)
                            .addComponent(DobleHabaneroCon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(HamburguezasMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(HamburguezasMenuLayout.createSequentialGroup()
                                .addGap(86, 86, 86)
                                .addGroup(HamburguezasMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(HamburguezasMenuLayout.createSequentialGroup()
                                        .addGap(13, 13, 13)
                                        .addComponent(jLabel11))
                                    .addComponent(jLabel25))
                                .addGap(18, 18, 18))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, HamburguezasMenuLayout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jLabel31)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(EspecialImg, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(31, 31, 31)))
                        .addGroup(HamburguezasMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Especial)
                            .addGroup(HamburguezasMenuLayout.createSequentialGroup()
                                .addComponent(EspecialCon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel32)))))
                .addContainerGap(46, Short.MAX_VALUE))
        );
        HamburguezasMenuLayout.setVerticalGroup(
            HamburguezasMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HamburguezasMenuLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(HamburguezasMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(HamburguezasMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(Sencilla)
                        .addGroup(HamburguezasMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, HamburguezasMenuLayout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(28, 28, 28)
                                .addGroup(HamburguezasMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(SencillaImg, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(SencillaCon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel26)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, HamburguezasMenuLayout.createSequentialGroup()
                                .addGroup(HamburguezasMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(HamburguezasMenuLayout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addGap(2, 2, 2)
                                        .addComponent(jLabel3))
                                    .addComponent(Hawaiana))
                                .addGap(12, 12, 12)
                                .addGroup(HamburguezasMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(HawaianaImg, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(HawaianaCon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel27)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, HamburguezasMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(HamburguezasMenuLayout.createSequentialGroup()
                                    .addComponent(Doble)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(HamburguezasMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(DobleImg, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(DobleCon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel28)))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, HamburguezasMenuLayout.createSequentialGroup()
                                    .addComponent(jLabel4)
                                    .addGap(97, 97, 97)))))
                    .addGroup(HamburguezasMenuLayout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(6, 6, 6)
                        .addGroup(HamburguezasMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(HamburguezasMenuLayout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGap(18, 18, 18)
                                .addGroup(HamburguezasMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(HabaneroImg, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(HabaneroCon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel29)))
                            .addComponent(Habanero))))
                .addGap(6, 6, 6)
                .addGroup(HamburguezasMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(HamburguezasMenuLayout.createSequentialGroup()
                        .addGroup(HamburguezasMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(HamburguezasMenuLayout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addGap(6, 6, 6)
                                .addComponent(jLabel10))
                            .addComponent(DobleHabanero))
                        .addGap(18, 18, 18)
                        .addGroup(HamburguezasMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(DobleHabanaeroImg, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(DobleHawaianaCon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(DobleHabaneroCon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel30)
                            .addComponent(jLabel31)))
                    .addGroup(HamburguezasMenuLayout.createSequentialGroup()
                        .addGroup(HamburguezasMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(HamburguezasMenuLayout.createSequentialGroup()
                                .addComponent(jLabel11)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel25))
                            .addComponent(Especial))
                        .addGap(18, 18, 18)
                        .addGroup(HamburguezasMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(EspecialImg, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(HamburguezasMenuLayout.createSequentialGroup()
                                .addGap(13, 13, 13)
                                .addGroup(HamburguezasMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(EspecialCon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel32)))))
                    .addGroup(HamburguezasMenuLayout.createSequentialGroup()
                        .addGroup(HamburguezasMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(HamburguezasMenuLayout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addComponent(jLabel7)
                                .addGap(6, 6, 6)
                                .addComponent(jLabel8))
                            .addGroup(HamburguezasMenuLayout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addComponent(DobleHawaiana)))
                        .addGap(18, 18, 18)
                        .addComponent(DobleHawaianaImg, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        MenuComida.addTab("Hamrguesas", HamburguezasMenu);

        ExtrasMenu.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                ExtrasMenuMouseMoved(evt);
            }
        });
        ExtrasMenu.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                ExtrasMenuPropertyChange(evt);
            }
        });

        jLabel12.setText("Brochetas de Pollo");

        jLabel13.setText("Papas a la Francesa");

        jLabel14.setText("Alitas");

        Brochetas.add(BBQ);
        BBQ.setText("BBQ");
        BBQ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BBQActionPerformed(evt);
            }
        });

        Brochetas.add(MangoHab);
        MangoHab.setText("Mango Habanero");

        OrdenPapas.setText("Orden de papas");

        jLabel15.setText("Precio: ");

        jLabel16.setText("Precio: ");

        Alitas.add(OrdenAlitas12);
        OrdenAlitas12.setText("Orden de 12 Pzas");
        OrdenAlitas12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OrdenAlitas12ActionPerformed(evt);
            }
        });

        Alitas.add(OrdenAlitas6);
        OrdenAlitas6.setText("Orden de 6 Pzas");

        PrecioBrochetas.setText("$40 Pesos");

        PrecioPapas.setText("$40 Pesos");

        jLabel19.setText("Precio: ");

        javax.swing.GroupLayout ExtrasMenuLayout = new javax.swing.GroupLayout(ExtrasMenu);
        ExtrasMenu.setLayout(ExtrasMenuLayout);
        ExtrasMenuLayout.setHorizontalGroup(
            ExtrasMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ExtrasMenuLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ExtrasMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ExtrasMenuLayout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addGap(179, 179, 179)
                        .addComponent(jLabel13))
                    .addComponent(MangoHab)
                    .addGroup(ExtrasMenuLayout.createSequentialGroup()
                        .addGroup(ExtrasMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(BBQ)
                            .addGroup(ExtrasMenuLayout.createSequentialGroup()
                                .addComponent(jLabel15)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(PrecioBrochetas)))
                        .addGap(174, 174, 174)
                        .addGroup(ExtrasMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(OrdenPapas)
                            .addGroup(ExtrasMenuLayout.createSequentialGroup()
                                .addComponent(jLabel16)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(PrecioPapas)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 328, Short.MAX_VALUE)
                .addGroup(ExtrasMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel14)
                    .addComponent(OrdenAlitas6)
                    .addComponent(OrdenAlitas12)
                    .addGroup(ExtrasMenuLayout.createSequentialGroup()
                        .addComponent(jLabel19)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(PrecioAlitas)))
                .addGap(29, 29, 29))
        );
        ExtrasMenuLayout.setVerticalGroup(
            ExtrasMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ExtrasMenuLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ExtrasMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(jLabel13)
                    .addComponent(jLabel14))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 104, Short.MAX_VALUE)
                .addGroup(ExtrasMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ExtrasMenuLayout.createSequentialGroup()
                        .addGroup(ExtrasMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(BBQ)
                            .addComponent(OrdenPapas))
                        .addGap(18, 18, 18)
                        .addComponent(MangoHab))
                    .addGroup(ExtrasMenuLayout.createSequentialGroup()
                        .addComponent(OrdenAlitas12)
                        .addGap(18, 18, 18)
                        .addComponent(OrdenAlitas6)))
                .addGap(18, 18, 18)
                .addGroup(ExtrasMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ExtrasMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel15)
                        .addComponent(jLabel16)
                        .addComponent(PrecioBrochetas)
                        .addComponent(PrecioPapas))
                    .addGroup(ExtrasMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel19)
                        .addComponent(PrecioAlitas)))
                .addGap(37, 37, 37))
        );

        MenuComida.addTab("Extras", ExtrasMenu);

        ContenidoPago.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                ContenidoPagoMouseMoved(evt);
            }
        });

        jLabel33.setText("Total a pagar:");

        TotalPagar.setText("$0 Pesos");

        Pagar.setText("Pagar");

        Regresar.setText("Regresar");

        Agregar.setText("Agregar");
        Agregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AgregarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout ContenidoPagoLayout = new javax.swing.GroupLayout(ContenidoPago);
        ContenidoPago.setLayout(ContenidoPagoLayout);
        ContenidoPagoLayout.setHorizontalGroup(
            ContenidoPagoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ContenidoPagoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ContenidoPagoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ContenidoPagoLayout.createSequentialGroup()
                        .addComponent(jLabel33)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(TotalPagar)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ContenidoPagoLayout.createSequentialGroup()
                        .addComponent(Regresar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Agregar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Pagar)))
                .addContainerGap())
        );
        ContenidoPagoLayout.setVerticalGroup(
            ContenidoPagoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ContenidoPagoLayout.createSequentialGroup()
                .addGap(85, 85, 85)
                .addGroup(ContenidoPagoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel33)
                    .addComponent(TotalPagar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 56, Short.MAX_VALUE)
                .addGroup(ContenidoPagoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ContenidoPagoLayout.createSequentialGroup()
                        .addGroup(ContenidoPagoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Pagar)
                            .addComponent(Agregar))
                        .addContainerGap())
                    .addComponent(Regresar, javax.swing.GroupLayout.Alignment.TRAILING)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(MenuComida)
            .addComponent(ContenidoPago, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jSeparator1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(MenuComida, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(ContenidoPago, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void EspecialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EspecialActionPerformed
        if (Especial.isSelected()) {
            EspecialCon.setEnabled(true);
            PrecioEspecial = 80;
            totalPago();

        } else {
            EspecialCon.setEnabled(false);
            EspecialCon.setValue(1);
            PrecioEspecial = 0;
            totalPago();
        }
    }//GEN-LAST:event_EspecialActionPerformed

    private void OrdenAlitas12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OrdenAlitas12ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_OrdenAlitas12ActionPerformed

    private void BBQActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BBQActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BBQActionPerformed

    private void SencillaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SencillaActionPerformed
        if (Sencilla.isSelected()) {
            SencillaCon.setEnabled(true);
            PrecioSensilla = 45;
            totalPago();

        } else {
            SencillaCon.setEnabled(false);
            SencillaCon.setValue(1);
            PrecioSensilla = 0;
            totalPago();

        }
    }//GEN-LAST:event_SencillaActionPerformed

    private void HawaianaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HawaianaActionPerformed
        if (Hawaiana.isSelected()) {
            HawaianaCon.setEnabled(true);
            PrecioHawaiana = 50;
            totalPago();
        } else {
            HawaianaCon.setEnabled(false);
            HawaianaCon.setValue(1);
            PrecioHawaiana = 0;
            totalPago();

        }
    }//GEN-LAST:event_HawaianaActionPerformed

    private void DobleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DobleActionPerformed
        if (Doble.isSelected()) {
            DobleCon.setEnabled(true);
            PrecioDoble = 60;
            totalPago();

        } else {
            DobleCon.setEnabled(false);
            DobleCon.setValue(1);
            PrecioDoble = 0;
            totalPago();

        }
    }//GEN-LAST:event_DobleActionPerformed

    private void HabaneroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HabaneroActionPerformed
        if (Habanero.isSelected()) {
            HabaneroCon.setEnabled(true);
            PrecioSalsaHab = 60;
            totalPago();

        } else {
            HabaneroCon.setEnabled(false);
            HabaneroCon.setValue(1);
            PrecioSalsaHab = 0;
            totalPago();
        }
    }//GEN-LAST:event_HabaneroActionPerformed

    private void DobleHawaianaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DobleHawaianaActionPerformed
        if (DobleHawaiana.isSelected()) {
            DobleHawaianaCon.setEnabled(true);
            PrecioDobleHawai = 65;
            totalPago();

        } else {
            DobleHawaianaCon.setEnabled(false);
            DobleHawaianaCon.setValue(1);
            PrecioDobleHawai = 0;
            totalPago();
        }
    }//GEN-LAST:event_DobleHawaianaActionPerformed

    private void DobleHabaneroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DobleHabaneroActionPerformed
        if (DobleHabanero.isSelected()) {
            DobleHabaneroCon.setEnabled(true);
            PrecioDobleHab = 65;
            totalPago();

        } else {
            DobleHabaneroCon.setEnabled(false);
            DobleHabaneroCon.setValue(1);
            PrecioDobleHab = 0;
            totalPago();
        }
    }//GEN-LAST:event_DobleHabaneroActionPerformed

    private void SencillaConStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_SencillaConStateChanged
        if (Sencilla.isSelected()) {
            SencillaCon.setEnabled(true);
            int numeroSencillas;
            int PagarSencilla = 45;
            numeroSencillas = (Integer) SencillaCon.getValue();
            PrecioSensilla = PagarSencilla * numeroSencillas;
            System.out.println("Precio de Sencilla " + PrecioSensilla);
            totalPago();

        } else {
            SencillaCon.setEnabled(false);
            SencillaCon.setValue(1);
            PrecioSensilla = 0;
            totalPago();
        }


    }//GEN-LAST:event_SencillaConStateChanged

    private void HawaianaConStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_HawaianaConStateChanged
        int numeroHawaiana;
        int PagarHawaiana = 50;
        numeroHawaiana = (Integer) HawaianaCon.getValue();
        PrecioHawaiana = PagarHawaiana * numeroHawaiana;
        System.out.println("Precio de Hawaiana " + PrecioHawaiana);
        totalPago();
    }//GEN-LAST:event_HawaianaConStateChanged

    private void DobleConStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_DobleConStateChanged
        if (Doble.isSelected()) {
            DobleCon.setEnabled(true);
            int numeroSencillas;
            int PagarSencilla = 60;
            numeroSencillas = (Integer) DobleCon.getValue();
            PrecioDoble = PagarSencilla * numeroSencillas;
            System.out.println("Precio de Doble " + PrecioSensilla);
            totalPago();

        } else {
            SencillaCon.setEnabled(false);
            SencillaCon.setValue(1);
            PrecioSensilla = 0;
            totalPago();
        }
    }//GEN-LAST:event_DobleConStateChanged

    private void HabaneroConStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_HabaneroConStateChanged
        if (Habanero.isSelected()) {
            HabaneroCon.setEnabled(true);
            int numeroSencillas;
            int PagarSencilla = 60;
            numeroSencillas = (Integer) HabaneroCon.getValue();
            PrecioSalsaHab = PagarSencilla * numeroSencillas;
            System.out.println("Precio de Habanero " + PrecioSalsaHab);
            totalPago();

        } else {
            SencillaCon.setEnabled(false);
            SencillaCon.setValue(1);
            PrecioSensilla = 0;
            totalPago();
        }
    }//GEN-LAST:event_HabaneroConStateChanged

    private void DobleHawaianaConStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_DobleHawaianaConStateChanged
        if (DobleHawaiana.isSelected()) {
            DobleHawaianaCon.setEnabled(true);
            int numeroSencillas;
            int PagarSencilla = 60;
            numeroSencillas = (Integer) DobleHawaianaCon.getValue();
            PrecioDobleHawai = PagarSencilla * numeroSencillas;
            System.out.println("Precio de DobleHawaiana " + PrecioDobleHawai);
            totalPago();

        } else {
            SencillaCon.setEnabled(false);
            SencillaCon.setValue(1);
            PrecioSensilla = 0;
            totalPago();
        }
    }//GEN-LAST:event_DobleHawaianaConStateChanged

    private void DobleHabaneroConStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_DobleHabaneroConStateChanged
        if (DobleHabanero.isSelected()) {
            DobleHabaneroCon.setEnabled(true);
            int numeroSencillas;
            int PagarSencilla = 60;
            numeroSencillas = (Integer) DobleHabaneroCon.getValue();
            PrecioDobleHab = PagarSencilla * numeroSencillas;
            System.out.println("Precio de DobleHabanero " + PrecioDobleHab);
            totalPago();

        } else {
            SencillaCon.setEnabled(false);
            SencillaCon.setValue(1);
            PrecioSensilla = 0;
            totalPago();
        }
    }//GEN-LAST:event_DobleHabaneroConStateChanged

    private void EspecialConStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_EspecialConStateChanged

    }//GEN-LAST:event_EspecialConStateChanged

    private void MenuComidaStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_MenuComidaStateChanged

    }//GEN-LAST:event_MenuComidaStateChanged

    private void MenuComidaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MenuComidaMouseClicked

    }//GEN-LAST:event_MenuComidaMouseClicked

    private void AgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AgregarActionPerformed
        Pagar.setVisible(true);
        HamburguezasMenu.setVisible(true);
        MenuComida.setSelectedIndex(0);

    }//GEN-LAST:event_AgregarActionPerformed

    private void MenuComidaPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_MenuComidaPropertyChange
    }//GEN-LAST:event_MenuComidaPropertyChange

    private void ExtrasMenuPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_ExtrasMenuPropertyChange

    }//GEN-LAST:event_ExtrasMenuPropertyChange

    private void ExtrasMenuMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ExtrasMenuMouseMoved
        int variable = 0;
        variable = MenuComida.getSelectedIndex();
        if (variable == 1) {
            Pagar.setVisible(false);
            brochetas();
            ordenPapas();
            ordenAlitas();
            totalPago();
            System.out.println("entro");
        } else {
            System.out.println("nada");
            Pagar.setVisible(true);

        }
    }//GEN-LAST:event_ExtrasMenuMouseMoved

    private void ContenidoPagoMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ContenidoPagoMouseMoved
        int variable = 0;
        variable = MenuComida.getSelectedIndex();
        if (variable == 0) {
            Pagar.setVisible(true);
        }
    }//GEN-LAST:event_ContenidoPagoMouseMoved
    public void totalPago() {
        precioReal = PrecioSensilla + BrochetaPollo + BrochetaHab + Papas + Alitas6 + Alitas12 + PrecioHawaiana + PrecioDoble + PrecioSalsaHab + PrecioDobleHawai + PrecioEspecial + PrecioDobleHab;
        System.out.println("VAlor de total pago: " + precioReal);
        TotalPagar.setText("$" + String.valueOf(precioReal) + " Pesos");
    }

    public void ordenPapas() {
        if (OrdenPapas.isSelected()) {
            Papas = 40;
            System.out.println(Papas);
        } else {
            Papas = 0;

        }
    }

    public void ordenAlitas() {
        if (OrdenAlitas12.isSelected()) {
            Alitas12 = 130;
            Alitas6 = 0;

            System.out.println(Alitas12);

            PrecioAlitas.setText("$ " + Alitas12 + " Pesos");
        } else if (OrdenAlitas6.isSelected()) {
            Alitas6 = 70;
            Alitas12 = 0;
            PrecioAlitas.setText("$ " + Alitas6 + " Pesos");

            System.out.println(Alitas6);

        } else {
            Alitas12 = 0;
            Alitas6 = 0;

        }
    }

    public void brochetas() {
        if (BBQ.isSelected()) {
            BrochetaPollo = 40;
            BrochetaHab = 0;

            System.out.println(BrochetaPollo);

        } else if (MangoHab.isSelected()) {
            BrochetaHab = 40;
            BrochetaPollo = 0;

            System.out.println(BrochetaHab);

        } else {
            BrochetaPollo = 0;
            BrochetaHab = 0;

        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Pedidos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Pedidos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Pedidos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Pedidos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new Pedidos().setVisible(true);

            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Agregar;
    private javax.swing.ButtonGroup Alitas;
    private javax.swing.JRadioButton BBQ;
    private javax.swing.ButtonGroup Brochetas;
    private javax.swing.JPanel ContenidoPago;
    private javax.swing.JCheckBox Doble;
    private javax.swing.JSpinner DobleCon;
    private javax.swing.JLabel DobleHabanaeroImg;
    private javax.swing.JCheckBox DobleHabanero;
    private javax.swing.JSpinner DobleHabaneroCon;
    private javax.swing.JCheckBox DobleHawaiana;
    private javax.swing.JSpinner DobleHawaianaCon;
    private javax.swing.JLabel DobleHawaianaImg;
    private javax.swing.JLabel DobleImg;
    private javax.swing.JCheckBox Especial;
    private javax.swing.JSpinner EspecialCon;
    private javax.swing.JLabel EspecialImg;
    private javax.swing.JPanel ExtrasMenu;
    private javax.swing.JCheckBox Habanero;
    private javax.swing.JSpinner HabaneroCon;
    private javax.swing.JLabel HabaneroImg;
    private javax.swing.JPanel HamburguezasMenu;
    private javax.swing.JCheckBox Hawaiana;
    private javax.swing.JSpinner HawaianaCon;
    private javax.swing.JLabel HawaianaImg;
    private javax.swing.JRadioButton MangoHab;
    private javax.swing.JTabbedPane MenuComida;
    private javax.swing.JRadioButton OrdenAlitas12;
    private javax.swing.JRadioButton OrdenAlitas6;
    private javax.swing.JRadioButton OrdenPapas;
    private javax.swing.JButton Pagar;
    private javax.swing.JLabel PrecioAlitas;
    private javax.swing.JLabel PrecioBrochetas;
    private javax.swing.JLabel PrecioPapas;
    private javax.swing.JButton Regresar;
    private javax.swing.JCheckBox Sencilla;
    private javax.swing.JSpinner SencillaCon;
    private javax.swing.JLabel SencillaImg;
    private javax.swing.JLabel TotalPagar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables
}
