package Ventanas;

import clases.*;
import java.sql.Connection;
import javax.swing.JOptionPane;
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author DanKuzo
 */
public class VentanaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form Prueba
     */
    public VentanaPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Login = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        Login1 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        Comida2 = new javax.swing.JLabel();
        Comida1 = new javax.swing.JLabel();
        Bebidas1 = new javax.swing.JLabel();
        Bebidas2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        Whatsapp = new javax.swing.JLabel();
        Facebook = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        Facebook1 = new javax.swing.JLabel();
        OpcionesAdmin = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("LaRanitApp");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Login.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/Login/login2.png"))); // NOI18N
        Login.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LoginMouseClicked(evt);
            }
        });
        jPanel1.add(Login, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 0, 100, 90));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 102, 0));
        jLabel1.setText("Bienvenido al rincon de la ranita");
        jLabel1.setAlignmentY(0.7F);
        jLabel1.setBorder(new org.edisoncor.gui.util.DropShadowBorder());
        jLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 400, 60));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 102, 0));
        jLabel2.setText("Iniciar Session");
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 90, 100, -1));

        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Login1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/Login/login2.png"))); // NOI18N
        Login1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Login1MouseClicked(evt);
            }
        });
        jPanel3.add(Login1, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 0, 100, 90));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 102, 0));
        jLabel8.setText("Bienvenido al rincon de la ranita");
        jLabel8.setAlignmentY(0.7F);
        jLabel8.setBorder(new org.edisoncor.gui.util.DropShadowBorder());
        jLabel8.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel3.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 400, 60));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 102, 0));
        jLabel9.setText("Iniciar Session");
        jLabel9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel9MouseClicked(evt);
            }
        });
        jPanel3.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 90, 100, -1));

        Comida2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        Comida2.setForeground(new java.awt.Color(255, 102, 0));
        Comida2.setText("Comida");
        Comida2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Comida2MouseClicked(evt);
            }
        });
        jPanel3.add(Comida2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 230, -1, -1));

        Comida1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/Restauran/icons8-hamburguesa-100.png"))); // NOI18N
        Comida1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Comida1MouseClicked(evt);
            }
        });
        jPanel3.add(Comida1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 130, 96, 96));

        Bebidas1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/Restauran/icons8-café-para-llevar-100.png"))); // NOI18N
        Bebidas1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Bebidas1MouseClicked(evt);
            }
        });
        jPanel3.add(Bebidas1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 130, 96, 96));

        Bebidas2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        Bebidas2.setForeground(new java.awt.Color(255, 102, 0));
        Bebidas2.setText("Bebidas");
        Bebidas2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Bebidas2MouseClicked(evt);
            }
        });
        jPanel3.add(Bebidas2, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 230, -1, -1));

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Redes Sociales", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 18), new java.awt.Color(255, 102, 0))); // NOI18N
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 102, 0));
        jLabel5.setText("Whatsapp");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 45, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 102, 0));
        jLabel6.setText("Facebook");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 45, -1, -1));

        Whatsapp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/Restauran/icons8-whatsapp-50.png"))); // NOI18N
        Whatsapp.setAlignmentX(5.0F);
        Whatsapp.setAlignmentY(5.0F);
        Whatsapp.setMaximumSize(new java.awt.Dimension(100, 14));
        jPanel2.add(Whatsapp, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 30, -1, -1));

        Facebook.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/Restauran/icons8-facebook-rodeado-de-círculo-50.png"))); // NOI18N
        Facebook.setAlignmentX(5.0F);
        Facebook.setAlignmentY(5.0F);
        Facebook.setMaximumSize(new java.awt.Dimension(100, 14));
        jPanel2.add(Facebook, new org.netbeans.lib.awtextra.AbsoluteConstraints(395, 30, -1, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 102, 0));
        jLabel7.setText("Telefono");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 45, -1, -1));

        Facebook1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/Restauran/icons8-phone-50.png"))); // NOI18N
        Facebook1.setAlignmentX(5.0F);
        Facebook1.setAlignmentY(5.0F);
        Facebook1.setMaximumSize(new java.awt.Dimension(100, 14));
        jPanel2.add(Facebook1, new org.netbeans.lib.awtextra.AbsoluteConstraints(245, 30, -1, -1));

        jPanel3.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 350, 540, 130));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 540, 480));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 540, 480));

        jMenu1.setText("Opciones");

        jMenu2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/Restauran/rana 16.png"))); // NOI18N
        jMenu2.setText("Ususario");

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_D, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/Restauran/rana 16.png"))); // NOI18N
        jMenuItem1.setText("Eliminar");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem1);

        jMenuItem2.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/Restauran/rana 16.png"))); // NOI18N
        jMenuItem2.setText("Actualizar");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem2);

        jMenu1.add(jMenu2);
        jMenu1.add(jSeparator2);

        jMenu3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/Restauran/rana 16.png"))); // NOI18N
        jMenu3.setText("Menu");

        jMenuItem3.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_D, java.awt.event.InputEvent.SHIFT_MASK));
        jMenuItem3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/Restauran/rana 16.png"))); // NOI18N
        jMenuItem3.setText("Eliminar");
        jMenu3.add(jMenuItem3);

        jMenuItem4.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.SHIFT_MASK));
        jMenuItem4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/Restauran/rana 16.png"))); // NOI18N
        jMenuItem4.setText("Actualizar");
        jMenu3.add(jMenuItem4);

        jMenu1.add(jMenu3);

        OpcionesAdmin.add(jMenu1);

        setJMenuBar(OpcionesAdmin);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void LoginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LoginMouseClicked
        IniciarSession();

    }//GEN-LAST:event_LoginMouseClicked

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        IniciarSession();
    }//GEN-LAST:event_jLabel2MouseClicked

    private void Login1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Login1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_Login1MouseClicked

    private void jLabel9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel9MouseClicked

    private void Comida1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Comida1MouseClicked
        menuComida();
    }//GEN-LAST:event_Comida1MouseClicked

    private void Comida2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Comida2MouseClicked
        menuComida();

    }//GEN-LAST:event_Comida2MouseClicked

    private void Bebidas1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Bebidas1MouseClicked
        menuBibida();

    }//GEN-LAST:event_Bebidas1MouseClicked

    private void Bebidas2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Bebidas2MouseClicked
        menuBibida();
    }//GEN-LAST:event_Bebidas2MouseClicked

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
         Eliminar eliminar = new Eliminar();
        eliminar.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        Actualizar actualizar = new Actualizar();
        actualizar.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jMenuItem2ActionPerformed
    public void IniciarSession() {
        Login l = new Login();
        l.setVisible(true);
        this.dispose();

    }

    public void menuComida() {
        Login login = new Login();
        if (login.getIdUsuario() != null) {
            Pedidos p = new Pedidos();
            p.setVisible(true);
            this.dispose();
        } else {
            System.out.println(login.getIdUsuario());
            JOptionPane.showMessageDialog(null, "Debes de Iniciar sesion o entrar como invitado");
        }
    }

    public void menuBibida() {
        System.out.println("hola bebida");
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Bebidas1;
    private javax.swing.JLabel Bebidas2;
    private javax.swing.JLabel Comida1;
    private javax.swing.JLabel Comida2;
    private javax.swing.JLabel Facebook;
    private javax.swing.JLabel Facebook1;
    private javax.swing.JLabel Login;
    private javax.swing.JLabel Login1;
    private javax.swing.JMenuBar OpcionesAdmin;
    private javax.swing.JLabel Whatsapp;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    // End of variables declaration//GEN-END:variables
Conectar cc = new Conectar();
    Connection cn = cc.conexion();
}
